# Generated by Django 5.0.2 on 2024-02-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='healine',
            new_name='headline',
        ),
    ]
